### ISSUE TITLE
add options menu in community item in home.

### ISSUE THREAD

**Issue by MuhammedEdrees** [SocialPlatformGP/social-multiplatform#20]

**Comment by MoZarea** [comment]
for admin 
- [ ] manage members
- [ ] leave
- [ ] delete
- [ ] edit name or des

for normal user

- [ ] leave
- [ ] show members
- [ ] Share Join Code

**Comment by MuhammedEdrees** [comment]
- [ ] Share Join Code
- [ ] Manage Members
- [ ] Leave
-  [ ] Edit Community
- [ ] Delete
